const mongoose = require('mongoose');
const IncidentReport = require('./models/IncidentReport');
const User = require('./models/User');
const fs = require('fs');
require('dotenv').config();

async function seedIncidents() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    
    // Create or find a specific Gemini AI user to own these reports
    let geminiUser = await User.findOne({ email: 'gemini@safeher.ai' });
    if (!geminiUser) {
      geminiUser = await User.create({
        name: 'Gemini AI Tracker',
        email: 'gemini@safeher.ai',
        password: 'SecurePassword123!',
        phone: '0000000000'
      });
    }

    // Read the incidents generated by Gemini
    const rawData = fs.readFileSync('massive_incidents.json', 'utf-8');
    const incidents = JSON.parse(rawData);

    // Delete existing reports by Gemini User so we don't duplicate on multiple runs
    await IncidentReport.deleteMany({ userId: geminiUser._id });

    // Format for DB
    const dbIncidents = incidents.map(inc => ({
      userId: geminiUser._id,
      category: inc.category,
      description: `✨ [Tracked by Gemini AI] - ${inc.description}`,
      location: {
        type: 'Point',
        coordinates: [inc.longitude, inc.latitude]
      },
      address: inc.address,
      isVerified: true
    }));

    await IncidentReport.insertMany(dbIncidents);
    console.log(`Successfully inserted ${dbIncidents.length} Gemini tracked incidents.`);
    
    process.exit(0);
  } catch (err) {
    console.error('Seeding error:', err);
    process.exit(1);
  }
}

seedIncidents();
